### ISSUE TITLE
Widok API symulacji walki

### ISSUE THREAD

**Issue by emkarcinos** [emkarcinos/WMIAdventure#167]
- [x] Efekt Zadawanie DMG #124 @Michael-Czekanski 
 - [x] Klasa BattleCalculator wyliczająca jedynie dmg zadawany przez karty z DMG @Michael-Czekanski 
- [ ] Listener w Coordinatorze @Michael-Czekanski 
- [ ] Serializer
- [ ] Widok

**Comment by Michael-Czekanski** [comment]
Issue przerobiono na milestone "Widok API Symulacji Walki" i rozbito na mniejsze issues
