### ISSUE TITLE
Dodanie favicon icon do aplikacji

### ISSUE THREAD

**Issue by emkarcinos** [emkarcinos/WMIAdventure#347]
Stworzenie i dodanie ikony favicon.ico, aby nie było już logo Reacta, tylko nasze własne.

To co jest teraz:

![image](https://user-images.githubusercontent.com/51495505/125649855-0e1c73b1-72ef-4d78-a08c-3921bc1cef10.png)

Dotyczy #339

**Comment by mattyl006** [comment]
Tutaj najlepiej moim zdanieć zrobić favicon wersję naszego logo - zielonego tuxa.

**Comment by emkarcinos** [comment]
Ja też jestem za tuxem (jest na figmie)
