### ISSUE TITLE
Design popupu z podglądem karty

### ISSUE THREAD

**Issue by emkarcinos** [emkarcinos/WMIAdventure#350]
Przy wyborze podglądu karty powinien wyświetlić się popup z widokiem tej karty. Trzeba to zaprojektować w wersji mobilnej i desktopowej.

- [ ] #332
- [ ] #333

**Comment by emkarcinos** [comment]
Pierwsza wersja:
- Mobilna
![image](https://user-images.githubusercontent.com/11946540/126307160-69aef8a5-a91a-4ea1-8ddb-27bcb72e81ee.png)
- Dekstopowa
![image](https://user-images.githubusercontent.com/11946540/126309184-71ef087b-ab32-4392-8e05-caad857f3bee.png)

**Comment by mattyl006** [comment]
@emkarcinos Bardzo fajne, ale widzę że robisz to tak, że trzeba będzie często wartości marginów tak na wyczucie robić, zakrąglać też, wielkości fontów na przykład. To nie jest w sumie duży problem, tylko informuje

**Comment by emkarcinos** [comment]
> @emkarcinos Bardzo fajne, ale widzę że robisz to tak, że trzeba będzie często wartości marginów tak na wyczucie robić, zakrąglać też, wielkości fontów na przykład. To nie jest w sumie duży problem, tylko informuje

A dasz mi jakieś wskazówki jak to robić? Bo trochę tego nie rozumiem, ja po prostu te marginesy ustawiam w Figmie, wszystko jest w layoutach, nie ma nigdzie żadnych itemów które się nie trzymają marginesów albo pozycjonowania

**Comment by mattyl006** [comment]
@emkarcinos chodzi o to, że jak użyje sobie alt w figmie to widzę co od czego jest odległe i o ile. W tych layoutach to pewnie musiałbyś ustawić, tam jest taki kwadracik gdzie się ustawia te odstępy.  
![image](https://user-images.githubusercontent.com/51495505/126447475-8390b0b7-762f-4118-8d7b-402f83f5137a.png)

Tutaj przykład, ta nazwa karty w ogóle nie ma odległości od przedmiotu
![image](https://user-images.githubusercontent.com/51495505/126447643-9b08b232-cead-4943-96e8-825426d33d07.png)

**Comment by Michael-Czekanski** [comment]
Ładne, mi się podoba. Z tymi odstępami i ogólnie wielkościami elementów to faktycznie fajnie jakby były wielokrotnościami 8, a wielkości czcionek to jakieś liczby całkowite

**Comment by emkarcinos** [comment]
Zaktualizowane.
![image](https://user-images.githubusercontent.com/11946540/126686776-4f40819f-a913-463b-9c2c-ee1991b08f80.png)
![image](https://user-images.githubusercontent.com/11946540/126686792-a5e0d5e2-4037-4440-8d62-2cf636b9b94d.png)
