### ISSUE TITLE
Design wyglądu karty w wersji kompaktowej

### ISSUE THREAD

**Issue by emkarcinos** [emkarcinos/WMIAdventure#352]
- [ ] #332
- [ ] #338 

W aplikacji będziemy potrzebować widok 'kompaktowy' karty, który może zawierać np tylko nazwę i ikonę. Wykorzystamy do w talii kart i w trybie battle do wyróżnienia kart, które nie są na wierzchu stosu. Dotyczy też #339

**Comment by emkarcinos** [comment]
Pierwsza wersja kompaktowej karty:
![image](https://user-images.githubusercontent.com/11946540/126130760-bcd186ee-81f7-4dcb-ab9a-9b54b7cba20d.png)
![image](https://user-images.githubusercontent.com/11946540/126130797-aba6e1d0-9e13-4038-892e-500e381346a7.png)

**Comment by Michael-Czekanski** [comment]
Dla mnie spoko to wygląda

**Comment by mattyl006** [comment]
@emkarcinos Fajne, a co z tymi tekstami humorycznymi dla kart? Warto teraz o tym myśleć czy przejmować się tym później?
Dla mnie mogłyby być po prostu rozdzielone akapitem/odstępem. Kwestia czy wszystko zawsze się ładnie pomieści.

**Comment by emkarcinos** [comment]
> @emkarcinos Fajne, a co z tymi tekstami humorycznymi dla kart? Warto teraz o tym myśleć czy przejmować się tym później?
> Dla mnie mogłyby być po prostu rozdzielone akapitem/odstępem. Kwestia czy wszystko zawsze się ładnie pomieści.

To jest w pełnej wersji karty. W tej kompaktowej to się nie zmieści. I nie wiem po co użytkownik miałby potrzebować tego opisu przy wyborze karty w talii, to raczej jest tutaj zbędne

**Comment by mattyl006** [comment]
@emkarcinos Tak o tą pełną mi chodziło, w złym miejscu napisałem. Kompaktowe git
