### ISSUE TITLE
Design popupów przy wysyłaniu karty

### ISSUE THREAD

**Issue by emkarcinos** [emkarcinos/WMIAdventure#353]
- [ ] #145

Aktualny popup przy wysyłaniu karty jest bardzo prototypowy i nie ma w nim żadnych istotnych informacji, poza tym czy udało się wysłać tą kartę czy nie.

Trzeba zaprojektować popup, który uwzględni pole na dodatkową wiadomość dla administratorów dołączoną do karty.

Popup z sukcesem / niepowodzeniem wysyłania karty też należy zaprojektować od zera z uwzględnieniem komunikatu błedu przy niepowodzeniu.

#339 #378

**Comment by mattyl006** [comment]
Nie jestem pewny tylko co do tego że tekst jest bardzo przyklejony do tej linii

![image](https://user-images.githubusercontent.com/51495505/126073574-9135d9ec-40c0-4d99-8df9-8cb410c69b4e.png)
![image](https://user-images.githubusercontent.com/51495505/126073583-89e0630a-e3a1-42b3-b799-5c70210878a4.png)
![image](https://user-images.githubusercontent.com/51495505/126073593-39358546-837a-4157-bc0c-bc268a20ff79.png)

**Comment by mattyl006** [comment]
@emkarcinos I jeszcze te odstępy. Np. w polach do Karty są chyba wszystkie symetrycznie:
![image](https://user-images.githubusercontent.com/51495505/126073642-9a4fcac8-2eea-4dfa-a6c5-6c2537e0a554.png)

A w tych popupach już nie:
![image](https://user-images.githubusercontent.com/51495505/126073659-3ea388a1-098d-4929-9f76-638ea3968282.png)

**Comment by emkarcinos** [comment]
Poprawiłem, zwiększyłem odstęp o 4px.

![image](https://user-images.githubusercontent.com/11946540/126124105-880629e7-5cb1-47c0-b936-34492122cf94.png)

**Comment by emkarcinos** [comment]
Symetryczne odstępy 
![image](https://user-images.githubusercontent.com/11946540/126124342-e53f4b2b-9c67-4729-bb84-deaf0be38428.png)

**Comment by mattyl006** [comment]
@emkarcinos Fajnie, teraz tylko kwestia tego, czy na wersji desktop ma to wyglądać tak samo, czy może np. z większymi odstępami?
Jeszcze nie jestem pewien w jaki sposób niektóre popupy powinny się pojawiać na wersji desktop. Np. ten z nazwą obrazkiem itp. wysuwa się z góry na mobile i to wygląda ok, ale na desktopie??

**Comment by Michael-Czekanski** [comment]
Też tak myślę, że na desktopie mogło by po prostu na środku wyskakiwać, wysuwane od góry raczej nie pasuje

**Comment by emkarcinos** [comment]
Wersja desktop
![image](https://user-images.githubusercontent.com/11946540/126297285-0909880c-cd0f-48c3-a7d6-4c37c7aa5dc4.png)

**Comment by mattyl006** [comment]
@emkarcinos Przy tych popupach zabrakło krzyżyków? Czy zostawiamy tak, i uznajemy że dla każdego użytkownika będzie oczywiste to, że gdy kliknie poza obszar to się zamknie. Bez krzyżyków może być estetyczniej, ale nie wiem co jest lepszą praktyką UX.

**Comment by mattyl006** [comment]
@emkarcinos Na desktopie ten popup z opisem ma też się rozszerzać pionowo tylko? Może jeszcze trochę powiększyć te na desktopie.

**Comment by emkarcinos** [comment]
Zaktualizowane:
![image](https://user-images.githubusercontent.com/11946540/126472152-f1662869-5902-43d3-bd33-9f0d28c4b941.png)

Zrobiłem tak jak sugerujesz. Zadbałem też o te marginesy tak jak wspominałeś

**Comment by mattyl006** [comment]
Spoczko
