### ISSUE TITLE
Wypełnienie textboxów aktualnymi danymi karty przy edycji

### ISSUE THREAD

**Issue by emkarcinos** [emkarcinos/WMIAdventure#367]
Gdy mamy już kartę, która ma wypełnione dane tekstowe (tytuł, opis, przedmiot), to przy ponownej próbie edytowania tych danych wszystkie textboxy są puste, przez co jeżeli chcemy zmienić tylko jedną literkę w tytule karty, to musimy na nowo wpisywać wszystko.

Textboxy powinny być zawsze wypełnione aktualnymi danymi żeby ułatwić edycję karty.

#334

**Comment by Michael-Czekanski** [comment]
W sumie u mnie i na desktopie i na mobilce textboxy są wypełnione aktualnymi danymi

**Comment by emkarcinos** [comment]
Jak wybierzesz kartę do edycji to nie są.
![Screenshot_20210721-085803.jpg](https://user-images.githubusercontent.com/11946540/126445363-a454864f-2b5d-44d6-929a-93d68c6d2ea0.jpg)![Screenshot_20210721-085808.jpg](https://user-images.githubusercontent.com/11946540/126445375-d469b722-7c2c-4feb-a783-255810b06626.jpg)

**Comment by Michael-Czekanski** [comment]
A faktycznie jakoś mi umknęło, że to na edycji karty
