### ISSUE TITLE
Aktualizacja designu Edytora o możliwość dodawania obrazu (ikony) do karty

### ISSUE THREAD

**Issue by emkarcinos** [emkarcinos/WMIAdventure#374]
We wcześniejszych planach odrzuciliśmy możliwość dodawania obrazów do karty. Teraz zdecydowaliśmy się uwzględnić obrazy jako "ikonę" widoczną w karcie, która dobrze ją zidentyfikuje i wyróżni graficznie.
Dotyczy #339 , #338 .

**Comment by mattyl006** [comment]
@emkarcinos Mi się podoba i nie dostrzegam żadnych problemów z tym.
