### ISSUE TITLE
Co z taskami na dokumentacje?

### ISSUE THREAD

**Issue by emkarcinos** [emkarcinos/WMIAdventure#380]

**Comment by mattyl006** [comment]
Moim zdaniem powinny być osobne taski na dokumentacje.

**Comment by emkarcinos** [comment]
Im dłużej o tym myślę tym bardziej skłaniam się ku temu, zeby robić osobne taski.
Poprzedni schemat pracy w ogóle nie wychodził, zapominalismy aktualizować to wiki. Poza tym, jakbyśmy mieli robić kilka tasków programistycznych pod rząd, to aktualizacja wiki mogłaby wywalać nas z transu.

**Comment by Michael-Czekanski** [comment]
Też tak myślę
