### ISSUE TITLE
Design page'a wyboru gracza do pojedynku (Mobile)

### ISSUE THREAD

**Issue by Michal-Czekanski** [emkarcinos/WMIAdventure#517]
Na tym page'u powinna być lista z innymi użytkownikami, których możemy wyzwać na pojedynek.

- [x] #67 
- [x] #65 
- [x] #66 
- [x] #78 
- [x] #79 
- [x] #77

**Comment by emkarcinos** [comment]
Wstępny design tego co wyjeżdża:
![image](https://user-images.githubusercontent.com/11946540/137601792-94ab43c5-1483-4785-8a55-ccf36a268927.png)

**Comment by emkarcinos** [comment]
![image](https://user-images.githubusercontent.com/11946540/137643217-5ae95361-adf4-4124-8d0e-09c731ae1114.png)
Złoty w tle to placeholder dla obrazka
