### ISSUE TITLE
Design wyniku walki (Mobile)

### ISSUE THREAD

**Issue by mattyl006** [emkarcinos/WMIAdventure#519]
#80 #74

**Comment by emkarcinos** [comment]
![image](https://user-images.githubusercontent.com/11946540/137772174-dfeda2dc-8bb5-45c1-966b-91c4ec4d5af5.png)

**Comment by mattyl006** [comment]
Może przenieśmy te paski WINNER i LOSER na dół jako przyciski, i tak jak w edytorze mobile jest z levelami. Jak klikniemy na WINNER to pokaże się wygrany a jak klikniemy na LOSER to przegrany. Jak wygramy to domyślnie będzie pokazany WINNER a gdy przegramy LOSER. Chyba że zdecydujemy się że może być ze scrollem, to wtedy tak może zostać, tylko te paski zwycięstwa/porażki będą mniejsze na 320px szerokości
