### ISSUE TITLE
Design widoku po wyborze gracza do walki (Mobile)

### ISSUE THREAD

**Issue by emkarcinos** [emkarcinos/WMIAdventure#528]
#69 #73 #101 #71

**Comment by emkarcinos** [comment]
Wstępnie
![image](https://user-images.githubusercontent.com/11946540/137626975-d838e4eb-e5da-4eed-aad1-7f769709a4ec.png)

**Comment by emkarcinos** [comment]
![image](https://user-images.githubusercontent.com/11946540/137643131-3afaee4c-212d-41a3-af1a-b5c5d37ac596.png)
Można już to implementować, te złote kwadraty to placeholdery na image.

**Comment by Michael-Czekanski** [comment]
Dla mnie git 👍
