### ISSUE TITLE
Aktualizacja designów wyniku walki o case z remisem

### ISSUE THREAD

**Issue by emkarcinos** [emkarcinos/WMIAdventure#601]
Zapomnieliśmy o case gdzie będzie remis - trzeba to jakoś zaprezentować użytkownikowi

**Comment by emkarcinos** [comment]
![image](https://user-images.githubusercontent.com/11946540/140650404-6953149b-b865-450a-82f5-69ae07838248.png)
![image](https://user-images.githubusercontent.com/11946540/140650408-471e449c-207a-4729-afd1-6cb7ed1a82c1.png)

**Comment by mattyl006** [comment]
Jak dla mnie spoko!
