### ISSUE TITLE
Design efektów

### ISSUE THREAD

**Issue by emkarcinos** [emkarcinos/WMIAdventure#607]
W #606 prowadzimy dyskusję na temat tego jak to zrobić

**Comment by mattyl006** [comment]
Myślałem o tym aby zrobić tak że:
1) Wysuwa sie karta ktora ma akcje
2) Z niej przed nią wysuwają się ikonki w zależności od ilości efektów np. 3
3) Mamy wysunieta karte i przed nia 3 ikonki
4) Gdy dany efekt sie wykonuje to odpowiednia ikonka robi animacje lekkiego powiekszenia sie a po tym pomniejszenia (cos w tym stylu jak te kuce loading tylko jednorazowo i wolniej)
5) I po tej animacji odpowiednio odjecie zycia, tarcza itp.
6) I po tym kolejna ikonka itd.
