### ISSUE TITLE
Redesign Navbar

### ISSUE THREAD

**Issue by emkarcinos** [emkarcinos/WMIAdventure#687]

**Comment by emkarcinos** [comment]
![image](https://user-images.githubusercontent.com/11946540/143945586-d8def406-8219-480b-a69b-94481576cd64.png)
![image](https://user-images.githubusercontent.com/11946540/143945627-c059bc9f-13dd-412a-92db-fe58c3e24881.png)

**Comment by emkarcinos** [comment]
![image](https://user-images.githubusercontent.com/11946540/144134159-95b359a6-c8fc-43f7-979f-eb9fe539aca8.png)

**Comment by Michal-Czekanski** [comment]
dla mnie fajny

**Comment by mattyl006** [comment]
ze środka usunąć te podpisy na desktopie i git

**Comment by emkarcinos** [comment]
![image](https://user-images.githubusercontent.com/11946540/144261905-cbfa76e2-4068-48a5-86e9-850008a5afc0.png)
