### ISSUE TITLE
Redesign strony startowej

### ISSUE THREAD

**Issue by emkarcinos** [emkarcinos/WMIAdventure#689]

**Comment by mattyl006** [comment]
Tak jak pisałem na telegramie, role takie jak *product owner*, *scrum master* w sekcji Autorzy bym usunął.

**Comment by mattyl006** [comment]
Kolejna sprawa: to jest task i do MOBILE i do DESKTOP? Chyba lepiej to rozdzielić i zacząć od MOBILE, wtedy już będzie można MOBILE od razu implementować przed skończeniem DESKTOP.

**Comment by mattyl006** [comment]
To tylko sugestia, jak Ci wygodniej, to na raz Mobile i Desktop też spoko

**Comment by emkarcinos** [comment]
- Desktop: 
![image](https://user-images.githubusercontent.com/11946540/146032665-5fd18aeb-f51e-4408-b41e-c7698072a098.png)

- Mobile:
![image](https://user-images.githubusercontent.com/11946540/146032736-9cff41c9-c309-414c-ae63-972f0f254c2e.png)

**Comment by emkarcinos** [comment]
Dobrze byłoby implementować te tła z SVG, jak ktoś będzie to robił to proszę się do mnie odezwać

**Comment by mattyl006** [comment]
Kompletnie mi nie pasują te przyciski "rejestracja" i "logowanie". Zamiast tego hamburgera w górnym prawym logu powinien być po prostu przycisk "Dołącz do nas"

**Comment by emkarcinos** [comment]
![image](https://user-images.githubusercontent.com/11946540/146040208-57ec6586-872e-4ec7-a6be-fe1da897b30b.png)
![image](https://user-images.githubusercontent.com/11946540/146040259-bc76e64d-93bf-4eca-998b-708e428a03df.png)

**Comment by emkarcinos** [comment]
SVG: https://drive.google.com/drive/folders/10iPb59GxdpzfNu2VplEh_8mTM0qJoHV0?usp=sharing

**Comment by Michal-Czekanski** [comment]
Te nowe przyciski lepsze o wiele

**Comment by mattyl006** [comment]
accept
