### ISSUE TITLE
Redesign głównego menu

### ISSUE THREAD

**Issue by emkarcinos** [emkarcinos/WMIAdventure#690]

**Comment by mattyl006** [comment]
Zamiast (Adventure & Battle), powinien się tutaj pojawić (Edytor Kart & Battle). Można wykorzystać to co zrobił Grzesław, tylko jaki obrazek wstawić tam jako Edytor Kart? Może te karty? 

![image](https://user-images.githubusercontent.com/51495505/145802974-d0080d26-4dee-4372-b82e-743782d4b23b.png)

Pewnie Ty @emkarcinos wpadniesz na coś fajnego.

**Comment by emkarcinos** [comment]
A może mój profil i battle? Wydaje mi się, że to będą dwa najczęściej używane widoki

**Comment by emkarcinos** [comment]
Desktop:
![image](https://user-images.githubusercontent.com/11946540/146170696-1bb39105-96a9-464f-aa94-2bded67c46ef.png)
onHover dla tych przycisków powinien je przeskalować:
![image](https://user-images.githubusercontent.com/11946540/146170772-4e455163-63ff-48f1-a252-c8568e8ee35c.png)


Mobile:
![image](https://user-images.githubusercontent.com/11946540/146171124-5a53deb2-8867-46d1-924f-335a8be84dc4.png)

**Comment by mattyl006** [comment]
Na desktopie zapomniałeś tekstu podmienić na "Edytor Kart", pozostałość spoko

**Comment by mattyl006** [comment]
Jeszcze tak dla pewności; które elementy mają być png a które svg? Czy wszystko svg? Bo jak widzę te cienie to wydaje mi się że to trzeba png

**Comment by emkarcinos** [comment]
Wszystko jest w SVG, jako że tło jest białe, to nie ma co się przejmować cieniami

**Comment by mattyl006** [comment]
Czyli ostatecznie będzie bez cieni?

**Comment by emkarcinos** [comment]
Podmieniłem napisy na Figmie.

Czemu miałoby nie być cieni? Przecież na Figmie wrzucone jest SVG i wszystko jest OK

**Comment by mattyl006** [comment]
Nie do końca, Tux na koszulce Kuca jest nie ok

**Comment by emkarcinos** [comment]
https://drive.google.com/drive/folders/1-kTBtL2qH2z7bemaqD2vTqFnHZ9cYiMv?usp=sharing

**Comment by Michal-Czekanski** [comment]
Gites, tylko te rzeczy co Wirus pisał
