### ISSUE TITLE
Design Ekranu Logowania / Rejestracji

### ISSUE THREAD

**Issue by emkarcinos** [emkarcinos/WMIAdventure#691]
Discussion, bo nie wiadomo czy logowanie i rejestracja nie odbędzie się przez stronę USOSa

**Comment by Michal-Czekanski** [comment]
Ustaliliśmy na spotkaniu z Promotorem, że rezygnujemy z USOSa

**Comment by Michal-Czekanski** [comment]
### Register
![image](https://user-images.githubusercontent.com/43492764/144712657-1f31819f-511a-432e-a962-426d51db1762.png)

### Login
![image](https://user-images.githubusercontent.com/43492764/144712673-80c7745a-2400-4ea4-871b-f90d3ac3391b.png)

**Comment by Michal-Czekanski** [comment]
Poprawiłem, żeby okienka z errorami i bez errorów miały tą samą wysokość
