### ISSUE TITLE
Redesign wysuwanego Menu

### ISSUE THREAD

**Issue by emkarcinos** [emkarcinos/WMIAdventure#692]

**Comment by emkarcinos** [comment]
![image](https://user-images.githubusercontent.com/11946540/143951075-469d361e-a13e-4908-9d21-abe280e29a8e.png)

**Comment by emkarcinos** [comment]
- Na mobilce jako slide ![image](https://user-images.githubusercontent.com/11946540/143951503-0674b9f9-6626-4354-b162-de6e7d2c8d5c.png)
- Na desktopie jako onHover 
![image](https://user-images.githubusercontent.com/11946540/143952416-9ebba1df-03af-422b-acd8-f226f95d2792.png)

**Comment by emkarcinos** [comment]
Jak klikniemy na skromnosctopotega to nas przekieruje do UserProfile

**Comment by Michal-Czekanski** [comment]
podoba mi się 👍

**Comment by mattyl006** [comment]
spoko
