### ISSUE TITLE
Treści do strony startowej

### ISSUE THREAD

**Issue by emkarcinos** [emkarcinos/WMIAdventure#693]

**Comment by mattyl006** [comment]
Póki co mam taki template:

# Treść strona startowa Wmi

## Nagłówek h1
Wmi Adventure

## Podtytuł
Poznaj alternatywny świat studiowania na Wmi.

## CO NA CIEBIE CZEKA? (sekcje)

### Karty ze świata informatyki
...

### Pojedynki
...

### Bądź również twórcą!
...

### Rośnij w siłę!
...

### Aplikacja dostępna na każdym urządzeniu
...

### Jesteśmy open source!
...


## AUTORZY (bez ról, każdy powinien napisać krótko o sobie w kontekście wmi adventure)

### Mateusz

### Marcin

### Michał

### Dawid

**Comment by mattyl006** [comment]
Pomyślałem, że 6 tych mini sekcji będzie dobrze wyglądać tak jak jest na aktualnej wersji.
Zamiast "Pojedynki" może coś w stylu "Taktyczne pojedynki". Co ogólnie myślicie o takim template?

**Comment by mattyl006** [comment]
Pierwsza mini sekcja (draft):

### Karty ze świata informatyki
Podczas studiów oraz przygód z programowaniem poznajemy wiele różnorodnych rzeczy oraz pojęć. Czasami wręcz nie możemy zapomnieć o pewnych technologicznych niuansach czy przeżyciach, choć bardzo byśmy chcieli. Bez obaw! Wmi Adventure zapewni, że te wspomnienia jeszcze bardziej będą Ciebie nękać, ponieważ wszystko w tej aplikacji opiera się na kartach, które je reprezentują.

**Comment by mattyl006** [comment]
Druga (draft):

### Pojedynki
Stwórz swoją własną talię kart wybierając swoją ulubioną piątkę! Po co? Aby się pojedynkować oczywiście! Życie to wieczna walka o przeżycie i pamięć RAM. Na studiach również objawia się ta rywalizacja, która budzi w nas czasami dzikie emocje. Dlatego stworzyliśmy możliwość wyzwolenia tych uczuć poprzez walkę informatycznymi kartami ze studentami, prowadzącymi oraz absolwentami. Chcesz udowodnić, że jesteś lepszy? Masz ochotę zobaczyć jakiś rezultat na monitorze po X godzinach nieudanego kodowania? Włącz Wmi Adventure, zbierz karty a następnie wyzwyj kogoś na pojedynek!

**Comment by mattyl006** [comment]
Cała treść update:

# Treść strona startowa Wmi

## Nagłówek h1
Wmi Adventure

## Podtytuł
Poznaj alternatywny świat studiowania na Wmi.

## CO NA CIEBIE CZEKA? (sekcje)

### Karty ze świata informatyki
Podczas studiów oraz przygód z programowaniem poznajemy wiele różnorodnych rzeczy oraz pojęć. Czasami wręcz nie możemy zapomnieć o pewnych technologicznych niuansach czy przeżyciach, choć bardzo byśmy chcieli. Bez obaw! Wmi Adventure zapewni, że te wspomnienia jeszcze bardziej będą Ciebie nękać, ponieważ wszystko w tej aplikacji opiera się na kartach, które je reprezentują.

### Pojedynki
Życie to wieczna walka o przetrwanie i pamięć RAM. Na studiach objawia się rywalizacja, która budzi w nas czasami dzikie emocje. Dlatego stworzyliśmy możliwość wyzwolenia tych uczuć poprzez walkę informatycznymi kartami ze studentami, prowadzącymi oraz absolwentami. Chcesz udowodnić, że jesteś lepszy? Masz ochotę zobaczyć jakiś rezultat na monitorze po X godzinach nieudanego kodowania? Włącz Wmi Adventure, zbierz karty a następnie wyzwyj kogoś na pojedynek!

### Bądź również twórcą!
Każdy posiada własne skojarzenia i ulubione aspekty ze studiów na Wmi lub świata IT. Nasza platforma udostępnia możliwość tworzenia własnych kart, które po akceptacji przez administrację będą gotowe stanąć na polu bitwy! To miejsce potrzebuje takich ludzi jak Ty, ponieważ każde informatyczne doświadczenie pozwoli je wzbogacić. Istotnej roli nie grają tutaj jedynie Twoje umiejętności bitewne, ale również kreatywność!

### Rośnij w siłę!
Razem z ilością wygranych pojedynków i stworzonych przez Ciebie kart Twój poziom doświadczenia będzie wzrastać. Osiągając kolejne poziomy będziesz otrzymywać punkty nauki za które masz możliwość ulepszać swoje ulubione karty. Nie daj się wyprzedzić innym! Jeśli będziesz najbardziej pomysłowy oraz regularnie będziesz miażdżyć swoich przeciwników możesz stać się najpotężniejszy na Wmi!

### Aplikacja dostępna na każdym urządzeniu
Jedziesz aktualnie tramwajem? Jesteś na spacerze? Kodzisz właśnie microshella? To wszystko nie jest ważne, ponieważ zawsze możesz odpalić Wmi Adventure na dowolnym sprzęcie. Zapewniamy pełen dostęp zarówno na komputery osobiste jak i na telefonach komórkowych.

### Jesteśmy open source!
Jesteś ciekawy jak aplikacja jest zbudowana? Chciałbyś zaproponować lub wprowadzić jakieś zmiany? Nie ma problemu! Wmi Adventure to projekt open source, który jest otwarty na wszelkie sugestie i rozwój. Zapraszamy na nasze repozytorium na githubie po więcej informacji.

**Comment by Michal-Czekanski** [comment]
najs!

**Comment by emkarcinos** [comment]
> Podczas studiów oraz przygód z programowaniem poznajemy wiele różnorodnych rzeczy oraz pojęć.

Podczas studiów oraz przygód z programowaniem poznajemy wiele **różnych** rzeczy oraz pojęć.

> Czasami wręcz nie możemy zapomnieć o pewnych technologicznych niuansach czy przeżyciach, choć bardzo byśmy chcieli

Czasami wręcz nie możemy zapomnieć o pewnych technologicznych niuansach czy przeżyciach.

> Bez obaw! Wmi Adventure zapewni, że te wspomnienia jeszcze bardziej będą Ciebie nękać, ponieważ wszystko w tej aplikacji opiera się na kartach, które je reprezentują.

Bez obaw! **WMI** Adventure zapewni, że te wspomnienia jeszcze bardziej będą **Cię** nękać, ponieważ wszystko w tej aplikacji opiera się na **reprezentujących je kartach.**

> Na studiach objawia się rywalizacja...

Na studiach **pojawia się** rywalizacja...

> Masz ochotę zobaczyć jakiś rezultat na monitorze po X godzinach nieudanego kodowania?

Masz ochotę zobaczyć jakiś rezultat na monitorze po **setkach godzin** nieudanego kodowania?

> Nasza platforma udostępnia możliwość tworzenia własnych kart

Nasza platforma **pozwala na tworzenie** własnych kart

> które po akceptacji przez administrację będą gotowe stanąć na polu bitwy!

**które będą stawać na polu bitwy!*8

>  Istotnej roli nie grają tutaj jedynie Twoje umiejętności bitewne, ale również kreatywność!

**Twoje umiejętności nie grają tutaj jedynej istotnej roli,** ale również kreatywność!

> Osiągając kolejne poziomy będziesz otrzymywać punkty nauki za które masz możliwość ulepszać swoje ulubione karty

Osiągając kolejne poziomy będziesz **zdobywać** punkty nauki za które **ulepszysz** swoje ulubione karty

> Zapewniamy pełen dostęp zarówno na komputery osobiste jak i na telefonach komórkowych.

Zapewniamy pełen dostęp na komputery i **smartfony**
