### ISSUE TITLE
Logowanie i rejestracja na backendzie

### ISSUE THREAD

**Issue by emkarcinos** [emkarcinos/WMIAdventure#700]
Aktualnie możemy zalogować się na dowolnego użytkownika bez hasła. Nie wiemy też na ile endpoint z rejestracją jest bezpieczny.

Trzeba zrobić reseach jak to też wygląda z USOSem zanim to zrobimy.

Jeżeli rejestracja / logowanie będzie odbywać się po stronie USOSa, trzeba to jakoś zgrać z backendem, żeby np profile użytkownika stworzyły się przy rejestracji

Dokumentacja powinna być utworzona na to jak zarządzamy użytkownikami między naszym serwisem a USOSem

**Comment by mattyl006** [comment]
Hmm, Usosa chyba zrobimy w skrajnie optymistycznym przypadku. Ale jeśli to nie problem, to super byłoby to zrobić w taki sposób, że łatwo tego Usosa będzie można podpiąć.
