### ISSUE TITLE
Implementacja designu logowania i rejestracji / M

### ISSUE THREAD

**Issue by emkarcinos** [emkarcinos/WMIAdventure#701]
Design z #691

**Comment by mattyl006** [comment]
Tym również mogę się zająć, przy takich rzeczach czasami html i css to męczarnia.

**Comment by emkarcinos** [comment]
Design jest w sumie ready, możesz na razie zaimplementować sam wygląd i potem poczekać aż backend to ogarnie i wtedy się do niego wpiąć

**Comment by mattyl006** [comment]
@emkarcinos a no tak, bo Michał robił to już, no to biorę taska
