### ISSUE TITLE
Redesign widoku profilu użytkownika

### ISSUE THREAD

**Issue by emkarcinos** [emkarcinos/WMIAdventure#705]

**Comment by emkarcinos** [comment]
Mobile:
![image](https://user-images.githubusercontent.com/11946540/144049147-4caac761-b0b0-4aa9-8c2d-2a64564b2ae1.png)

Desktop szeroki:
![image](https://user-images.githubusercontent.com/11946540/144049190-e95aa64d-1a07-436b-9294-f950bbb2d257.png)

Desktop wąski:
![image](https://user-images.githubusercontent.com/11946540/144049215-2b6aed02-95cf-4dab-b525-feada3f17b99.png)

**Comment by emkarcinos** [comment]
Popup edytowania profilu:
![image](https://user-images.githubusercontent.com/11946540/144053389-37e96acb-2377-4961-ae39-c3ab447587eb.png)

![image](https://user-images.githubusercontent.com/11946540/144053409-13cc9326-cd7d-4003-8cb2-f3d0b0072fdb.png)
![image](https://user-images.githubusercontent.com/11946540/144053426-b26f4a63-2b07-4e76-b195-518d1793cc54.png)

**Comment by Michal-Czekanski** [comment]
na popupie by się przydał by się przycisk "zapisz"

**Comment by Michal-Czekanski** [comment]
ten navbar to narazie prototypowy jest?

![image](https://user-images.githubusercontent.com/43492764/144103885-eb715c1c-59ed-4433-a0fc-2a08419d87af.png)

**Comment by emkarcinos** [comment]
navbar jest z designu z #687

**Comment by emkarcinos** [comment]
![image](https://user-images.githubusercontent.com/11946540/144134042-4baf7c64-6c72-4b4f-84fe-00c64d0435ae.png)
![image](https://user-images.githubusercontent.com/11946540/144134063-7675c650-7b1a-4609-9d59-303bdfb37d79.png)

**Comment by Michal-Czekanski** [comment]
Jak dla mnie gites i gotowe

**Comment by mattyl006** [comment]
Może coś w stylu "cancel" albo krzyżyk w tym edytuj profil

**Comment by emkarcinos** [comment]
![image](https://user-images.githubusercontent.com/11946540/144264237-20f111d4-4c8f-44f4-9a6f-0e4535ff46c0.png)

![image](https://user-images.githubusercontent.com/11946540/144264270-01d59211-2fe4-47a5-9b66-d48f21c4e6f7.png)


Który wariant? Z dodatkowym przyciwkiem powrotu czy bez?

**Comment by emkarcinos** [comment]
Bierzemy z dwoma przyciskami
