### ISSUE TITLE
Statystyki naszego kodu do prezentacji

### ISSUE THREAD

**Issue by Michal-Czekanski** [emkarcinos/WMIAdventure#739]
Trzeba zebrać statystyki takie jak liczba linii kodu w danym języku, test coverage itp.

**Comment by mattyl006** [comment]
co masz na myśli poprzez "test coverage"?

**Comment by Michal-Czekanski** [comment]
ile procent kodu jest pokryte testami, w pycharmie jest coś takiego wbudowane chyba
