### ISSUE TITLE
Design Edytora Talii

### ISSUE THREAD

**Issue by emkarcinos** [emkarcinos/WMIAdventure#745]

**Comment by emkarcinos** [comment]
Desktop:
![image](https://user-images.githubusercontent.com/11946540/144928366-1d3070ee-ea89-4b3f-b710-d481e3fe80b6.png)

Mobile:
![image](https://user-images.githubusercontent.com/11946540/144928409-0bea3e65-c363-42ad-81e5-4b8f1470b18d.png)

**Comment by Michal-Czekanski** [comment]
Super

**Comment by emkarcinos** [comment]
Zmieniłem jeszcze widoki SwipeProfile na mobilce żeby można było tam edytować deck (dodałem podpis zamiast przycisku):
![image](https://user-images.githubusercontent.com/11946540/145093796-790e4c6c-429e-4787-a598-9901cd6515ce.png)

To samo na desktopie:
![image](https://user-images.githubusercontent.com/11946540/145093946-d01efa2c-832f-435a-89cf-9080bee3caf1.png)

**Comment by Michal-Czekanski** [comment]
Git
