### ISSUE TITLE
Testy obciążeniowe, dokumentacja potestowa

### ISSUE THREAD

**Issue by Michal-Czekanski** [emkarcinos/WMIAdventure#760]
Przydatne narzędzie do testów obciążeniowych: [vegeta](https://www.scaleway.com/en/docs/tutorials/load-testing-vegeta/)

Trzeba zrobić dokumentację z testów jakie są u nas w projekcie:
- testy jednostkowe
- testy integracyjne
- testy obciążeniowe

Trzeba też zrobić statystyki kodu takie jak np. pokrycie kodu testami

**Comment by mattyl006** [comment]
czyli symulacja 1000 userów na przykład, i czy nie będzie wtedy kosmicznie lagować
