### ISSUE TITLE
Możliwość zobaczenia profilu przeciwnika

### ISSUE THREAD

**Issue by emkarcinos** [emkarcinos/WMIAdventure#764]

**Comment by mattyl006** [comment]
Czyli nie tylko możemy wyzwać przeciwnika na pojedynek, ale zobaczyć jego profil. Jednak mam nadzieję że zostaniemy przy tym że karty są niewidoczne. Pozostałe dane takie jak lvl, ratio itd. powinny być widoczne.

**Comment by emkarcinos** [comment]
Ja w sumie jak zacząłem się nad tym bardziej zastanawiać, to nie wiem czy w ogóle tego potrzebujemy.
Mamy teraz widok OpponentSelected, który w sumie wyświetla wszystkie dane, które możemy pokazać o przeciwniku. 
Jakbyśmy weszli na taki pełny widok profilu przeciwnika tak samo jak widzimy nasz, to pół ekranu byłaby pusta, bo nie byłoby widać kart.

Nie wiem, czy nie przerzucić tego na później, bo ten widok może być bardziej istotny jak będziemy mieli na przykład zdobyte karty, albo rankingi (czyli pewnie już poza scope projektu inżynierskiego)

**Comment by mattyl006** [comment]
@emkarcinos w sumie racja, jak klikamy na przeciwnika to w `OpponentSelected` i tak wszystko widzimy, to chyba niepotrzebne, bo już jest ta "możliwość zobaczenia profilu użytkownika" właśnie poprzez `OpponentSelected`
