### ISSUE TITLE
W swipe profile jeszcze bardziej zmniejszyć czcionkę nazwy karty (od 5 znaków), opcjonalnie zwiększyć rozmiar samych kompaktowych kart jeśli wystarczy miejsca

### ISSUE THREAD

**Issue by mattyl006** [emkarcinos/WMIAdventure#780]

**Comment by Michal-Czekanski** [comment]
Ogólnie co zapamiętałem ze spotkania to obserwować po ilu znakach się załamuje linia i stworzyć odpowiednio reguły zmniejszania czcionek, by nie było takiego załamywania.
