### ISSUE TITLE
Aktualizacja kart na prod

### ISSUE THREAD

**Issue by emkarcinos** [emkarcinos/WMIAdventure#793]
W kartach na produkcji brakuje opisów i obrazków, trzeba je uzupełnić.

**Comment by mattyl006** [comment]
Mogę się tym zająć, bo mam jakieś pomysły. Dodatkowo zmodyfikowałbym trochę kart, bo czasami są chyba za OP.
Tylko zrobić to jakoś requestami? Czy za pomocą *admin/*? Dotychczas jak u siebie coś modyfikowałem to robiłem to poprzez edytor kart tak jak użytkownik + */accept* w *proposal content*.

**Comment by emkarcinos** [comment]
Ja też tak robiłem, ale @Michal-Czekanski wspominał, że może porobić akcje w tym panelu admina

**Comment by Michal-Czekanski** [comment]
Tak, mogę je pyknąć dzisiaj

**Comment by mattyl006** [comment]
@Michal-Czekanski to dawaj na to taska jeśli nie ma

**Comment by Michal-Czekanski** [comment]
cyk https://github.com/emkarcinos/WMIAdventure/pull/818

**Comment by emkarcinos** [comment]
https://drive.google.com/drive/folders/10E_QDosDzjC5a5U3expvz7pKOdJs1tZz?usp=sharing

**Comment by emkarcinos** [comment]
Startowe decki trzeba też zaktualizować https://github.com/emkarcinos/WMIAdventure/issues/855
