### ISSUE TITLE
Aktualizacja deploymentu dla prod

### ISSUE THREAD

**Issue by emkarcinos** [emkarcinos/WMIAdventure#794]
Chcemy korzystać z takiego samego pipeline jak w przypadku deploymentu na deva (Azure). Trzeba tylko zmienić build parametry na dane i hasła te pod produkcję.

**Comment by mattyl006** [comment]
Czyli tu jest ogarnięcie, aktualizacji dla wmi-adventure.pl ?

**Comment by emkarcinos** [comment]
Trzeba zaktualizować pipeline w GitHub actions. Aktualny korzysta jeszcze z tego docker compose, który serwuje devową wersję frontendu z watchem itp. Prawdopodobnie wystarczy skopiować to co jest aktualnie w pipeline przy CI/CD w samym deployu, ale nie wiem czy tagi obrazów nie powinny być jakieś inne żeby to działało
