### ISSUE TITLE
Pole `level` w widoku UserProfile

### ISSUE THREAD

**Issue by emkarcinos** [emkarcinos/WMIAdventure#795]
Mając gotowe poziomy użytkowników dobrze byłoby wyświetlać podstawową wartość liczbową w widoku z profilem. Dobrze to zrobić tutaj jako jedno dodatkowe pole z intem, bo frontend wyświetla level przy każdym użytkowniku i nie byłoby wtedy trzeba robić osobnego requesta aby taki level dostać. Dodatkowo pomoże to przy cachowaniu.

Nie przechowujemy danych o poziomie, tylko o samym zdobytym exp, więc to jaki poziom ma gracz powinno być wyliczone (#802)

**Comment by mattyl006** [comment]
czyli do *api/user-profile* dojdzie pole level
