### ISSUE TITLE
Nowy widok z informacją o poziomie danego profilu

### ISSUE THREAD

**Issue by emkarcinos** [emkarcinos/WMIAdventure#796]
W #795 chcemy dodać prostą wartość liczbową reprezentującą poziom. Dodatkowo będziemy potrzebowali takich informacji jak aktualne exp i exp potrzebne do osiągnięcia następnego poziomu. Proponuję stworzyć nowy endpoint dostępny pod `user-profiles/{id}/level`, który dostarczy nam informacji o
- aktualnym poziomie
- zdobytym exp
- exp potrzebnym do awansu na kolejny poziom

**Comment by mattyl006** [comment]
Czyli z tego będziemy korzystać w #809 ?

**Comment by emkarcinos** [comment]
Całkiem możliwe że tak koniec końców zrobimy, ale główny case to #803 gdzie będziemy pokazywać na froncie przy profilu ile mamy exp (jeżeli w ogóle zdecydujemy się to robić)
