### ISSUE TITLE
Dodanie pola ze zdobytym exp do serializera Battle

### ISSUE THREAD

**Issue by emkarcinos** [emkarcinos/WMIAdventure#797]
Frontend będzie chciał wyświetlić graczowi zdobyte doświadczenie po walce. Dobrym rozwiązaniem będzie dodanie pola w `outcome` nazwanego np `expGain`, które powie ile expa zdobyliśmy.

**Comment by mattyl006** [comment]
Czyli serializer do battle będzie miał kolejne pole `expGain`, rozumiem.
