### ISSUE TITLE
Model i serializer expa

### ISSUE THREAD

**Issue by emkarcinos** [emkarcinos/WMIAdventure#798]
Chcemy mieć dostępne w bazie dane o tym ile dany gracz ma zdobytych punktów doświadczenia.

Nie chcemy przechowywać takich danych jak poziom czy potrzebny exp do osiągnięcia następnego, bo to dane które powinny być przeliczane on demand w serializerze.

Sam serializer powinien spełniać wymagania z #796 i #795.

Logika biznesowa powinna być oddzielona od samego serializera (#802)

**Comment by mattyl006** [comment]
Implementacja serializera który robi odpowiednie rzeczy z exp, a do bazy danych tylko ile globalnie użytkownik ma pkt doświadczenia.

**Comment by emkarcinos** [comment]
Tak. Proponuję takie rozwiązanie, bo
- Trzymanie danych o poziomie i potrzebnym exp do kolejnego poziomu razem z całym exp jest redundantne
- Spodziewam się, że będziemy często dopasowywali wyliczanie tych poziomów itp, jakbyśmy mieli wartości na sztywno w bazie, to zmiana tej formułki wymagałaby zapuszczenia migracji
- Level i potrzebne exp łatwo zcachować już na backendzie
