### ISSUE TITLE
Signal dodający punkty exp do profilu

### ISSUE THREAD

**Issue by emkarcinos** [emkarcinos/WMIAdventure#799]
Chcemy rozdawać graczom punkty za odbyte pojedynki i za zaakceptowane do systemu karty. W tym celu przyda się signal, który doda danemu użytkownikowi punkty exp zdobyte za daną akcję.

**Comment by mattyl006** [comment]
Czyli implementacja sygnału, który powiadomi Backend o zdobytym exp za daną akcje/rezultat.

**Comment by emkarcinos** [comment]
Signal to taki event listener na backendzie. Frontend nic nie będzie powiadamiał backendu, tylko widok A będzie powiadamiał widok B

**Comment by mattyl006** [comment]
Aaa, rozumiem
