### ISSUE TITLE
Dokumentacja mechaniki zdobywania punktów i formuł poziomów

### ISSUE THREAD

**Issue by emkarcinos** [emkarcinos/WMIAdventure#800]
Na ostatnim spotkaniu obmyśliliśmy z promotorem dość sensowne formuły matematyczne kryjące się za poziomami i expem za pojedynki. Warto to udokumentować na wiki aby detale implementacyjne były jasno określone.

Mieliśmy wątpliwość co do funkcji odpowiedzialnej za wyliczanie expa potrzebnego do zdobycia kolejnych poziomów, trzeba też to sprecyzować i udokumentować.

Dodatkowo, na frontendzie kolorujemy ramki poziomów w zależności od jego wysokości, trzeba to też ustalić tutaj.

**Comment by mattyl006** [comment]
Zrobiłbym to tak:
- 1 pkt - przegrana
- zaokrąglone w dół sqrt(lvl przeciwnika) - remis
- zaokrąglone w dół (6 + sqrt(nasz lvl) + (lvl przeciwnika) - wygrana
- zaokrąglone w dół (10 + sqrt(nasz lvl)) - stworzenie karty, która zostanie zaakceptowana

Zdobywanie lvl:
1. na początku lvl: 0
2. aby osiągnąć 1 lvl: 10
3. 2 lvl: 20
4. 3 lvl: 30
5. 4 lvl: 50
6. i tak Fibonaccim do 11 lvl:  1440
7. potem kwadratowo, aby wolniej rosło, ale nie pamiętam jak to szło

(5: 80, 6: 130, 7: 210, 8: 340, 9: 550, 10: 890, 11: 1440, 12: byłby teoretycznie 2330)

Kolorowałbym ramkę na złotą od momentu osiągnięcia tego przejcia z Fib na Kwadratowe. A epicki jeszcze dalej,
może na 32 lvl. 32 to 2 do potęgi 5, a na inżynierce mamy 5 semestrów - super easter egg. A tak serio to nie wiem.

**Comment by Michal-Czekanski** [comment]
Zrobiłem draft pull request, trochę inaczej tam zapisałem w dokumencie, najlepiej będzie na tym dokumencie robić komentarze i tam dyskutować

**Comment by Michal-Czekanski** [comment]
https://github.com/emkarcinos/WMIAdventure/wiki/System-punkt%C3%B3w
