### ISSUE TITLE
Rozszerzenie logiki biznesowej w Battle o zdobywanie exp za pojedynki

### ISSUE THREAD

**Issue by emkarcinos** [emkarcinos/WMIAdventure#801]
Korzystając z #800 trzeba zaimplementować mechanizmy zdobywania punktów exp za pojedynki. Dobrym miejscem na to są klasy logiki biznesowej Battle.

**Comment by mattyl006** [comment]
Ok, czyli tutaj implementacja czegoś takiego jak to:
![image](https://user-images.githubusercontent.com/51495505/145729738-88fa20b6-3012-4a11-adb6-be1e20af37ec.png)
