### ISSUE TITLE
Wyliczanie poziomów na podstawie punktów exp

### ISSUE THREAD

**Issue by emkarcinos** [emkarcinos/WMIAdventure#802]
Poziomy stanowią ważną część logiki biznesowej i powinniśmy zarezerwować dla nich szczególne miejsce na backendzie. Trzeba zaimplementować design z #800 i wykorzystać go w #798 , #797 i #796.

**Comment by mattyl006** [comment]
- czyli najpierw robimy #800,
- tutaj robimy taki myk że mamy liczbę expa z której wnioskujemy który mamy lvl
- tą globalną liczbę expa przechowujemy w bazie i nic więcej (#798)
- nie czaje trochę powiązania z #797
- tutaj czaję, że ma to związek z #796 bo robimy w tym tasku wniosek który mamy lvl na podstawie globalnej liczby posiadanego expa

**Comment by emkarcinos** [comment]
#796 ma przechowywać:
- aktualny poziom
- aktualne exp
- exp do następnego poziomu

W #797 dodajemy tylko inta z aktualnym poziomem do każdego usera.
