### ISSUE TITLE
Storage/Gateway dla poziomów użytkowników

### ISSUE THREAD

**Issue by emkarcinos** [emkarcinos/WMIAdventure#805]
Aby wyświetlać dane we frontendzie potrzebujemy rozszerzyć storage o obsługę widoku z poziomami (aktualny poziom, exp, exp potrzebny do kolejnego poziomu).

Backend upubliczni endpoint z #796.

**Comment by mattyl006** [comment]
Super, raczej dokładnie tego będziemy potrzebować wszędzie.
1. Nasz aktualny poziom
2. Nasza aktualna wartość exp w aktualnym poziomie
3. Pozostała wartość exp potrzebna do kolejnego poziomu
