### ISSUE TITLE
Wyświetlanie prawdziwych poziomów przy użytkownikach

### ISSUE THREAD

**Issue by emkarcinos** [emkarcinos/WMIAdventure#806]
Aktualnie wyświetlamy placeholderowe dane o poziomie użytkowników. Backend dodaje pole z poziomiem do każdego użytkownika, więc storage powinien automatycznie obsługiwać te atrybuty.

**Comment by mattyl006** [comment]
Czyli rozumiem, że będzie to zaimplementowane po wykonaniu #805. Po tym gdy zrobimy tak, aby levele się zwiększały, to sprawę załatwi odpowiedni GET ze `storage/`. Trzeba w tym tasku zaaktualizować wartości w `UserLabel`, oraz `UserStatistic` ale tylko wartość liczbową.

**Comment by emkarcinos** [comment]
Nie, aktualny storage we frontendzie przechowuje już dane od userów z backendu. Zmienimy tylko serializer na backendzie i na froncie nie będzie trzeba nic zmieniać, tylko wykorzystać nowe dane w komponentach. `storage/` nie istnieje, storage to obszar we froncie gdzie zarządzamy danymi z backendu

**Comment by mattyl006** [comment]
`storage/` miałem na myśli katalog na froncie
