### ISSUE TITLE
Wyświetlanie zdobytego exp po walce

### ISSUE THREAD

**Issue by emkarcinos** [emkarcinos/WMIAdventure#808]

**Comment by mattyl006** [comment]
Analogicznie tak jak jest w walce zadawanie obrażeń, leczenie oraz dodawanie pancerza. To również w tym przypadku podświetliłbym tak pasek z tym lvl który się odpowiednio zwiększy.

**Comment by emkarcinos** [comment]
Na Figmie obecnie jest + ile exp dostaliśmy, to trzeba zaimplementować
