### ISSUE TITLE
Jak obsłużyć case gdy po walce zdobywamy nowy poziom?

### ISSUE THREAD

**Issue by emkarcinos** [emkarcinos/WMIAdventure#809]
W `PostBattle` będziemy prezentowali zdobyte exp podczas walki. Jest to prosta wartość do wyświetlenia, wyświetlamy +X EXP i animujemy pasek. Co w przypadku gdy zdobycie tego expa skuktuje awansem na nowy poziom? Zrobienie tego na frontendzie nie jest problematyczne, natomiast frontend musi mieć wiedzę o tym, że dany poziom został przekroczony. Trzeba zatem podjąc decyzję jak to obsłużyć.

**Comment by mattyl006** [comment]
Potrzebny tutaj GET, który na podstawie obecnego lvl użytkownika powie nam jaka jest wartość do następnego. Jeśli pasek osiągnie wartość następnego poziomu to wyskoczy odpowiedni PopUp z informacją o zdobyciu nowego levela i ilością naszych obecnie posiadanych pkt nauki.

**Comment by emkarcinos** [comment]
Nie wiem czy dodatkowy popup jest tutaj potrzebny, wg mnie można to ładnie zaprezentować na PostBattle dodając jakiś tekst przy tym + exp.

Co to nowych requestów to bym to możliwie ograniczył i spróbował np robić jakoś na frontendzie.

Punkty nauki na przyszły sprint

**Comment by mattyl006** [comment]
Co masz na myśli "robić jakoś na frontendzie"? Myślałem że tutaj wykorzystamy nowy endpoint z #796

**Comment by emkarcinos** [comment]
Możemy na frontendzie zrobić takie samo modelowanie jak przy Battle i wtedy moglibyśmy tam sprawdzać, czy nie zdobyliśmy czasem nowego poziomu po tym jak backend nam w outcome battle powie jaki mamy exp gain. Backend do niczego nie potrzebuje wtedy wiedzy, czy gracz zdobył nowy poziom, a frontend tak, bo chcemy to jakoś zaznaczyć wizualnie albo tak jak wspominałeś, pokazać popupa.

Zrobiłem na to osobnego taska bo właśnie to jest problem który może mieć kilka różnych rozwiązań i ja sam szczerze mówiąc nie wiem które jest optymalne. Sam bym to zrobił tak jak napisałem, żeby to obsłużyć na froncie, ale to tylko moja propozycja

**Comment by Michal-Czekanski** [comment]
Jeśli planujemy zrobić punkty za zgłaszanie karty to popup z wbijaniem levela może się przydać

**Comment by Michal-Czekanski** [comment]
Myśle, że tak jak mówisz Marcin moża by było zrobić na frontendzie też zrobić jakiś kod co sprawdza, czy gracz nie wbił następnego levela po jakimś exp gainie, bo przyda się to nie tylko przy walce. Co prawda narazie przyda się to tylko przy punktach za zgłaszanie kart, ale daje możliwości na przyszłość
