### ISSUE TITLE
Kolory poziomów

### ISSUE THREAD

**Issue by emkarcinos** [emkarcinos/WMIAdventure#810]
Nie sprecyzowaliśmy jeszcze jakie będą szczeble poziomów przy odpowiednich kolorach (typowy, złoty, epicki). W #800 ustalimy te szczeble. Trzeba to zaktualizować we frontendzie.

**Comment by mattyl006** [comment]
Tak jak napisałem w #800.
Kolorowałbym ramkę na złotą od momentu osiągnięcia tego przejcia z Fib na Kwadratowe. A epicki jeszcze dalej, na przykład na 32 lvl, na pewno w momencie gdzie jesteś w stanie mieć X epickich kart.

**Comment by Michal-Czekanski** [comment]
15 level złoty exp
