### ISSUE TITLE
Rate limiting

### ISSUE THREAD

**Issue by emkarcinos** [emkarcinos/WMIAdventure#812]
Obecnie jesteśmy narażeni na ataki typu DDOS. Nasze widoki backendowe serwują każdy request jednakowo, bez znaczenia na to jaki mamy ruch.

Poza samymi atakami DDOS możemy po prostu zabić backend przy jakimś dużym natłoku requestów, które mogą pojawić się jak z systemu będzie korzystać wielu użytkowników na raz.

Możemy zastosować mechanizm zwany rate limitingiem, który po osiągnięciu pewnych wartości requestów na sekunde zacznie je kolejkować i przekazywać dalej do widoków w kontrolowanym tempie, jest nawet do tego gotowa biblioteka do Django: https://django-ratelimit.readthedocs.io/en/stable/usage.html

Z tego co przeglądałem, powinno to być dosyć łatwe do skonfigurowania.

**Comment by Michal-Czekanski** [comment]
O kurde, dobrze by było to załatać
