### ISSUE TITLE
Brak połączenia z backendem powoduje printowanie exceptiona

### ISSUE THREAD

**Issue by emkarcinos** [emkarcinos/WMIAdventure#813]
Trzeba obsłużyć przypadek, gdy backend nie działa, obecnie dostajemy błąd na twarz. Trzeba to obsłużyć i nie pokazywać użytkownikowi programistycznych błędów.

**Comment by mattyl006** [comment]
Ja bym tutaj widział GenericPopUp z TransBack na fullscreen, z czymś w stylu "Nie udało się połączyć z serwerem" i przyciskiem "Spróbuj ponownie", który odświerza stronę.
