### ISSUE TITLE
Nowe Logo

### ISSUE THREAD

**Issue by emkarcinos** [emkarcinos/WMIAdventure#815]

**Comment by emkarcinos** [comment]
Wykorzystałem na razie logo Tuxa od Grzesława:
![image](https://user-images.githubusercontent.com/11946540/145730527-6a3e2e3f-5504-4434-bd6c-3e27ee5dc8de.png)

Tak to wygląda w innych widokach (Navbar)
![image](https://user-images.githubusercontent.com/11946540/145730543-3cf50a76-0bbd-4f7c-aa5a-142671497347.png)

![image](https://user-images.githubusercontent.com/11946540/145730552-c234134a-092e-4ca3-8f7b-9cdde50e437e.png)

**Comment by mattyl006** [comment]
Widzałbym tutaj tego zielonego Tuxa od Grzesława. Ewentualnie jeszcze z jakimś pasującym napisem "Wmi Adventure".

**Comment by mattyl006** [comment]
Jest dla mnie OK. Logo powinno być minimalistycznie. Ewentualnie jeszcze napis 'Wmi Adventure" przy nim jeśli masz jakiś pomysł na to

**Comment by emkarcinos** [comment]
![image](https://user-images.githubusercontent.com/11946540/145730788-e64665a6-a337-4e35-813a-e01a81f2cfe3.png)
A teraz?

**Comment by mattyl006** [comment]
To chyba teraz lepiej nie? Ewentualnie można jakiś bardziej fancy wyróżniający się font.

**Comment by emkarcinos** [comment]
Tylko fancy font się będzie gryzł z resztą designu. Dałem bolda i to już jest fancy, ale spróbuję coś wymyślić

**Comment by emkarcinos** [comment]
![image](https://user-images.githubusercontent.com/11946540/145731148-3301a962-6d9c-475e-a215-61aa9eb110fd.png)
A może taki terminalowy styl?

**Comment by mattyl006** [comment]
O fajny pomysł z nawiązaniem do terminala. Jak dla mnie spoko. Accept

**Comment by Michal-Czekanski** [comment]
Bardzo fajne
