### ISSUE TITLE
Chcę widzieć ile jeszcze mogę stoczyć walk zanim osiągnę limit czasowy, aby podejmować lepsze decyzje kogo i ile razy wyzwać na pojedynek

### ISSUE THREAD

**Issue by Michal-Czekanski** [emkarcinos/WMIAdventure#899]
Żeby gracz wiedział ile jeszcze walk może stoczyć

- [x] https://github.com/emkarcinos/WMIAdventure/issues/904
- [x] #932
- [x] #933
- [x] #934

**Comment by emkarcinos** [comment]
Przekształćmy to na user story, bo to bardzo szeroki task, i przede wszystkim bardziej biznesowy
