### ISSUE TITLE
Możliwość wyzwania 2 razy danego usera na pojedynek przed aktywacją limitu

### ISSUE THREAD

**Issue by mattyl006** [emkarcinos/WMIAdventure#904]
Myślę, że bardzo często gdy z kimś przegramy, będziemy chcieli zmienić talię i spróbować od razu jeszcze raz.
Po dwukrotnym pojedynku powinien aktywować się limit, na przykład że możemy walczyć z daną osobą dopiero po 2h ponownie dwa razy.

**Comment by emkarcinos** [comment]
Duplikat https://github.com/emkarcinos/WMIAdventure/issues/76 ?

**Comment by emkarcinos** [comment]
Trzeba to rozbić na mniejsze taski - UI/UX tutaj trzeba zrobić, frontend zaktualizować
