### ISSUE TITLE
Bug: Karty blokujące

### ISSUE THREAD

**Issue by wikti11** [emkarcinos/WMIAdventure#910]
**Opis błędu**
Można stworzyć deck wyłącznie z kart blokujących przeciwnika (lub 4 blokujących + np. Microshell) co powoduje darmowe zwycięstwo.

**Jak wywołać błąd?**
Wystarczy stworzyć deck tylko z kartami blokującymi przeciwnika.

**Oczekiwane działanie**
Podzielenie kart na grupy/klasy oraz wymuszenie na graczy używania maksymalnie 2 kart danej klasy/grupy.

***System i przeglądarka***
 - OS: Wszystkie
 - Browser: Wszystkie
 - Version: Najnowsza (30.12.2021)

**Dodatkowe informacje**
Poza tym zasugerowałbym możliwość sortowania graczy wg poziomu.

**Comment by mattyl006** [comment]
Dziękuję za zgłoszenie.
Zachęcam również do edycji istniejących kart aby je zbalansować.
Można na przykład zmodyfikować jakąś blokującą kartę w edytorze kart, usunąć moc blokady za jakąś alternatywę, co w konsekwencji będzie zapobiegać takim OP talią.
My oczywiście również będziemy starać się edytować karty i dbać o balans, aczkolwiek przypominam że wy jako użytkownicy również posiadacie taką możliwość.

**Comment by emkarcinos** [comment]
https://github.com/emkarcinos/WMIAdventure/issues/920

**Comment by emkarcinos** [comment]
Zabrakło nam czasu w bieżącym sprincie na rozwiązanie z #920, jako tymczasowy workaround zrobimy
- [ ] #931

**Comment by emkarcinos** [comment]
Duplikat #907, zamykam
