### ISSUE TITLE
Co ile lvl dawać ile punktów nauki?

### ISSUE THREAD

**Issue by mattyl006** [emkarcinos/WMIAdventure#916]
- [x] #922

**Comment by Michal-Czekanski** [comment]
Z tego co pamiętam na spotkaniu z Promotorem ustaliliśmy, że dobre będzie 1 punkt co poziom.

Ulepszanie:
- level złoty: 1 punkt
- level epicki: 2 punkty

Wtedy gracz na 15 poziomie mógłby mieć 5 epickich kart, w czymś się wyspecjalizować.

Co 3 level to bardzo wolno, późniejsze poziomy wbija się powoli. Wydaje mi się, że średnio zainteresowany gracz może czuć brak progresu

**Comment by emkarcinos** [comment]
Ustaliliśmy wstępnie, że co każdy poziom będziemy otrzymywać stałą liczbę punktów (na przykład 10) i koszty ulepszeń kart będziemy dostosowywać osobno

**Comment by Michal-Czekanski** [comment]
Zostanie ustalone w #922
