### ISSUE TITLE
Aktualizacja designu profilu użytkownika - wyświetlanie posiadanej liczby punktów nauki

### ISSUE THREAD

**Issue by Michal-Czekanski** [emkarcinos/WMIAdventure#917]
Punkty nauki - punkty do ulepszania kart.

**Comment by mattyl006** [comment]
Myślę że UserLabel z punktami nauki to najlepsza opcja
![image](https://user-images.githubusercontent.com/51495505/148052537-b43ec18a-7b98-4c29-83af-3b82d418ece2.png)

**Comment by emkarcinos** [comment]
Wersja 1 - key value z punktami nauki w widoku profilu:
![image](https://user-images.githubusercontent.com/11946540/148247772-59070821-56ce-4439-9ec8-d5de57743f77.png)
![image](https://user-images.githubusercontent.com/11946540/148247800-cafbfbfe-0afa-45af-a779-8512afce0909.png)


Wersja 2 - UserLabel - widok profilu i w Menubarze:
![image](https://user-images.githubusercontent.com/11946540/148248413-9fc3fe7b-2384-4a6a-905a-f09a322c7b00.png)
![image](https://user-images.githubusercontent.com/11946540/148248437-e8bde683-2a46-443f-bc7c-8ed4299410b7.png)
![image](https://user-images.githubusercontent.com/11946540/148248455-90675c6a-3164-4994-b3eb-f8e7763d53f8.png)

**Comment by mattyl006** [comment]
mmózg git

**Comment by Michal-Czekanski** [comment]
mózgi spoko

**Comment by emkarcinos** [comment]
Wybieramy mózgi

**Comment by Michal-Czekanski** [comment]
@emkarcinos  a kolory obramówki się tutaj jakoś zmienają w zależnosci od punktów?

**Comment by emkarcinos** [comment]
A obojętnie, zostawmy tak jak jest zaimplemejntowane teraz
