### ISSUE TITLE
W jaki sposób i gdzie wyświetlać informację, że użytkownik zdobył punkty?

### ISSUE THREAD

**Issue by Michal-Czekanski** [emkarcinos/WMIAdventure#918]
Po wbijaniu levela użytkownik zdobywa punkty. Być może kiedyś zrobimy zdobywanie punktów nie tylko za poziomy? Dobrze by to było zrobić w jakiś *loosly coupled* sposób, żeby dało się to łatwo ponownie użyć?

**Comment by emkarcinos** [comment]
Możemy zrobić popup po wbiciu poziomu / zdobyciu punktów nauki

**Comment by emkarcinos** [comment]
Możemy po walce przy awansie na kolejny poziom dostawać taki popup:
![image](https://user-images.githubusercontent.com/11946540/148251035-86266b82-ce05-41cc-8a22-b8710a1351a1.png)

**Comment by mattyl006** [comment]
spoko

**Comment by Michal-Czekanski** [comment]
gites
