### ISSUE TITLE
Ogłoszenie nowego feature Ulepszania Kart

### ISSUE THREAD

**Issue by Michal-Czekanski** [emkarcinos/WMIAdventure#923]
Pod koniec sprinta trzeba zdecydować, czy ogłaszamy nowy feature. Jeśli to robimy to w jaki sposób.

**Comment by emkarcinos** [comment]
Zdecydowaliśmy, że po releasie wyślemy do studentów maila z informacją o nowym updacie

**Comment by emkarcinos** [comment]
Cześć!

Pamiętacie jeszcze WMI Adventure? Jeżeli nie, to warto sobie przypomnieć, bo właśnie wypuściliśmy nową wersje! https://wmi-adventure.pl

W nowej wersji możecie odkryć następujące funkcje:
- Awansowanie na nowy poziom skutkuje zdobyciem punktów nauki - waluty wykorzystywanej w ulepszaniu kart
- Istniejące konta otrzymały punkty nauki za swoje poziomy
- Karty mają teraz wiele poziomów. Na początku wszyscy użytkownicy dostają karty o tym najniższym i mogą je ulepszyć za punkty nauki
- Nie wszystkie karty możemy ulepszać - niektóre nie mają wielu poziomów
- Nie możemy walczyć dwa razy z tym samym użytkownikiem przez określony czas (6 godzin)
- Przy przegranej z przeciwnikiem mamy możliwość rewanżu (jeden dodatkowy pojedynek)
- Wyświetlanie informacji o ilości dostępnych pojedynków przed walką
- Maksymalna wartość tarczy w pojedynkach wynosi teraz 50 (poprzednio 20)
- Lista przeciwników do walki jest teraz podzielona na strony

Każdy może przyczynić się do rozwoju WMI Adventure - jesteśmy open source, w aplikacji jest specjalna sekcja na sugestie - zachęcamy do wspólnego tworzenia :D

Dołącz do nas tutaj https://wmi-adventure.pl !
Team WMI Adventure
