### ISSUE TITLE
Samouczek

### ISSUE THREAD

**Issue by Michal-Czekanski** [emkarcinos/WMIAdventure#925]
Do prezentacji musimy przygotować samouczek

**Comment by emkarcinos** [comment]
Rozbijmy to na frontend i UX

**Comment by Michal-Czekanski** [comment]
popatrzyłem na figmie też na desktop i jest git tylko brakuje wytłumaczenia przycisków na desktopie

**Comment by emkarcinos** [comment]
A potrzebne są? Na desktopie domyślnie przyciski mają opis

**Comment by Michal-Czekanski** [comment]
a no w sumie niepotrzebne

**Comment by mattyl006** [comment]
spoko jest
