### ISSUE TITLE
Nie wyświetlać wszystkich użytkowników na raz w liście userów

### ISSUE THREAD

**Issue by mattyl006** [emkarcinos/WMIAdventure#928]
Nie wyświetlajmy wszystkich userów na raz, bo wtedy laguje. Najlepiej zaimplementować po stronie frontendu paginację z backendu.

**Comment by mattyl006** [comment]
10 albo 20 na stronę pewnie będzie ok

**Comment by emkarcinos** [comment]
Możemy obsłużyć poprawnie paginację na frontendzie - obecnie pobieramy każdą stronę z backendu po kolei i wrzucamy wszystko do jednego arraya z userami.

Myślę, że stary mechanizm można zostawić do wyszukiwania - można zrobić to sprytniej jeżeli użytkownicy są posortowani po nazwie, nawet ta defaultowa paginacja djangowa wspiera takie rzeczy po pokazuje jaki range liter jest na danej stronie. 

Chcemy mieć jednak sortowanie według poziomu (per #906) i wtedy już parametr wyszukiwania i sortowania się różni, więc na potrzeby wyszukiwania możemy pobrać tych wszystkich userów.

Jeżeli jednak chcemy żeby to wyszukiwanie było szybkie i sprawne to można dodać po prostu osobny parametr query do tego requesta z listą użytkowników który określi czy sortować po levelach (do wyświetlenia w komponencie) czy po nazwie (do wyszukiwania). Jako że czas nas goni, powiedziałbym że to overkill.


Nieważne jak będziemy pobierać te dane, trzeba też dostosować pod to cache i zastanowić się jak trzymać poszczególne strony, najlepiej pod jednym kluczem, każda strona jako osobny array.
