### ISSUE TITLE
Dodać istniejącym użytkownikom punkty nauki

### ISSUE THREAD

**Issue by emkarcinos** [emkarcinos/WMIAdventure#930]
~~Podjęliśmy decyzję, że zerujemy EXP wszystkim użytkownikom, żeby mogli przeżyć cały proces zdobywania punktów nauki i ulepszania kart od zera.~~

~~Zróbmy migrację w django, która wyzeruje exp wszystkim~~

Na spotkaniu zmieniliśmy decyzję, exp zostaje i istniejący użytkownicy będą mieli ten sam poziom i dostaną odpowiednią liczbę punktów nauki

**Comment by Michal-Czekanski** [comment]
możnaby to zrobić w łatwy sposób używając djangowego shella, ale musiałbym to przetestować lokalnie bo nie jestem pewien czy można wbić do kontenera dockerowego

**Comment by emkarcinos** [comment]
To warto byłoby wrzucić taki skrypt do repo mimo wszystko, jakby w przyszłości zaistniała potrzeba go uruchomić.
> ```python
> from IngameUsers.businesslogic.experience.Experience import Experience
> from IngameUsers.models import UserStats
> from IngameUsers.businesslogic.skill_points import calculate_skill_points_gain
> from django.db import transaction
> 
> with transaction.atomic():
> 	for user_stats in UserStats.objects.all():
> 		current_level = Experience(user_stats.exp).level
> 		skill_points = calculate_skill_points_gain(1, current_level)
> 		user_stats.skill_points = skill_points
> 		user_stats.save()
> ```

To nawet można wrzucić w migrację
