### ISSUE TITLE
Design powiadomienia o ilości dostępnych walk przy rate limitingu

### ISSUE THREAD

**Issue by emkarcinos** [emkarcinos/WMIAdventure#932]

**Comment by emkarcinos** [comment]
Mobile:
![image](https://user-images.githubusercontent.com/11946540/148280191-35ab4f7d-6c70-45e8-b7cb-7a1c314e4f4f.png)
Desktop:
![image](https://user-images.githubusercontent.com/11946540/148280394-9c6818b9-cef5-420c-8b67-fc779b2624ac.png)
(Logika na desktopie analogiczna do mobilnej)

**Comment by Michal-Czekanski** [comment]
fajny

**Comment by mattyl006** [comment]
gites
