### ISSUE TITLE
Serializer pojedynku powinien wysyłać dodatkowe informacje o kartach przeciwnika

### ISSUE THREAD

**Issue by emkarcinos** [emkarcinos/WMIAdventure#954]
Będziemy potrzebowali dodatkowo informację o poziomie karty.

**Comment by Michal-Czekanski** [comment]
na początku walki jest już przesyłany level
![image](https://user-images.githubusercontent.com/43492764/148575207-82c574f8-c0c4-4f89-8bc0-29a18471124e.png)

chyba, że chodzi o co innego?

**Comment by emkarcinos** [comment]
Faktycznie, zapomniałem o tym. Zamykam
