### ISSUE TITLE
W jaki sposób sortować użytkowników w trybie Battle

### ISSUE THREAD

**Issue by Michal-Czekanski** [emkarcinos/WMIAdventure#956]
Padła propozycja, aby sortować użytkowników po odległości od poziomu gracza, by ten widział podobnych do siebie na samej górze.

**Comment by Michal-Czekanski** [comment]
@emkarcinos  @mattyl006 to jak sortujemy? ja bym sortował jednak po prostu po największym lvl i jak będą jakieś jednak trudności związane ze znalezieniem graczy o podobnych poziomach to bym wtedy spróbował z tym sortowaniem po odległości od naszego poziomu

**Comment by emkarcinos** [comment]
> @emkarcinos  @mattyl006 to jak sortujemy? ja bym sortował jednak po prostu po największym lvl i jak będą jakieś jednak trudności związane ze znalezieniem graczy o podobnych poziomach to bym wtedy spróbował z tym sortowaniem po odległości od naszego poziomu

Ja tak samo, wg mnie po wysokości poziomu jest good enough

**Comment by mattyl006** [comment]
Tak, po wysokości poziomu wystarczy
