### ISSUE TITLE
Przenieść dawanie wszystkich kart do widoku API, gdzie zwracane są wszystkie karty usera

### ISSUE THREAD

**Issue by Michal-Czekanski** [emkarcinos/WMIAdventure#963]
Najpierw #929

Aktualnie w profilu użytkownika frontend wyciąga wszystkie karty z backendu. Gdy użytkownik modyfikuje swoją talię to dopiero wtedy dostaje wszystkie karty na backendzie (widok API `UserDeckView`).

Teraz na frontendzie będziemy korzystać z widoku, który zwraca wszystkie karty użytkownika zamiast z tego widoku co zwraca wszystkie "generyczne" karty z bazy. To w tym widoku użytkownik powinien dostawać wszystkie karty na backendzie, aby mieć dostęp do wszystkich kart w swoim profilu przy edycji talii.

**Comment by emkarcinos** [comment]
Czemu user powinien dostać wszystkie karty przy wywoływaniu jakiegoś requesta? Nie powinno to się dziać np wtedy gdy user się zarejestruje albo gdy zaakceptujemy nową kartę w systemie?
=

**Comment by Michal-Czekanski** [comment]
racja to będzie lepszy sposób
